### ISSUE TITLE
Refresh render

### ISSUE THREAD

**Issue by GiuseppeTG** [Daf98/Leaderboard#3]
### Highlights:

✔️  Very organized code
✔️  Easy to understand

### Issue

I noticed that every time you click on the refresh button, the list is displayed again under the previous one. Before refreshing it, you can empty your list so that the scores don't start to accumulate. 

Another thing (this is just for making the code look better) is that you can store the API URL in a `const` so that you don't have those long strings in your code so you can see better the final part of the URL you are using.
https://github.com/Daf98/Leaderboard/blob/f3ff54e05c3146c1e5d6338196c15baffe97f3fd/src/index.js#L11
The same can be done for the game id. The result is something like this: ``fetch(`${url}/games/${id}/scores/`)``

**Comment by Daf98** [comment]
Thank you @GiuseppeTG! I have solved both issues 😄
